drop table if exists account;
drop table if exists pet;
drop table if exists petowner;
drop table if exists petstore;

create table petstore (
    id integer generated by default as identity primary key,
    name varchar(20) not null,
    password varchar(20),
    balance integer not null
);

create table petowner (
    id integer generated by default as identity primary key,
    name varchar(20) not null,
    password varchar(20),
    money integer not null
);

create table pet (
    id integer generated by default as identity primary key,
    name varchar(20) not null,
    typename varchar(20),
    health integer,
    love integer,
    birthday timestamp,
    owner_id integer references petowner(id),
    store_id integer references petstore(id)
);

create table account (
    id integer generated by default as identity primary key,
    deal_type integer,
    pet_id integer references pet(id),
    seller_id integer,
    buyer_id integer,
    price integer,
    deal_time timestamp
);

insert into petstore(name, password, balance) values
('长沙宠爱一生宠物店', '123456', 600),
('武汉偶偶爱宠物店', '123456', 800);

insert into petowner(name, password, money) values
('tuling', '123456', 400),
('itboy', '123456', 200);

insert into pet(name, typename, health, love, birthday, owner_id, store_id) values
('花花', 'dog', 1, 50, '2010-02-02', 1, 1),
('贝贝', 'penguin', 1, 60, '2009-08-08', null, 2),
('成成', 'dog', 1, 70, '2013-03-03', null, 1),
('露露', 'bird', 1, 70, '2014-03-03', null, 1),
('老虎欧欧', 'tiger', 1, 20, '2010-03-03', 2, 1),
('老虎环环', 'tiger', 1, 20, '2010-03-03', null, 1),
('老虎美美', 'tiger', 1, 11, '2010-04-23', null, 1),
('狮子', 'lion', 0, 25, '2010-04-23', null, 2);
